:construction_worker: NEP29: Run Continuous Integration on Python 3.11 (#89)
Run Continuous Integration tests and workflows on Python 3.11. Need to bump pyproj, numpy, pandas, rasterio, fiona, pyogrio, toolz and shapely (plus a few others) to get versions with Python 3.11 wheels.

* :arrow_up: Bump pyproj from 3.3.1 to 3.4.1

Bumps [pyproj](https://github.com/pyproj4/pyproj) from 3.3.1 to 3.4.1.
- [Release notes](https://github.com/pyproj4/pyproj/releases)
- [Changelog](https://github.com/pyproj4/pyproj/blob/main/docs/history.rst)
- [Commits](https://github.com/pyproj4/pyproj/compare/3.3.1...3.4.1)

* :arrow_up: Bump numpy from 1.22.4 to 1.23.5

Bumps [numpy](https://github.com/numpy/numpy) from 1.22.4 to 1.23.5.
- [Release notes](https://github.com/numpy/numpy/releases)
- [Changelog](https://github.com/numpy/numpy/blob/main/doc/RELEASE_WALKTHROUGH.rst)
- [Commits](https://github.com/numpy/numpy/compare/v1.22.4...v1.23.5)

* :arrow_up: Bump pandas from 1.4.2 to 1.5.3

Bumps [pandas](https://github.com/pandas-dev/pandas) from 1.4.2 to 1.5.3.
- [Release notes](https://github.com/pandas-dev/pandas/releases)
- [Changelog](https://github.com/pandas-dev/pandas/blob/main/RELEASE.md)
- [Commits](https://github.com/pandas-dev/pandas/compare/v1.4.2...v1.5.3)

* :arrow_up: Bump rasterio from 1.3.2 to 1.3.6

Bumps [rasterio](https://github.com/rasterio/rasterio) from 1.3.0 to 1.3.6.
- [Release notes](https://github.com/rasterio/rasterio/releases)
- [Changelog](https://github.com/rasterio/rasterio/blob/main/CHANGES.txt)
- [Commits](https://github.com/rasterio/rasterio/compare/1.3.0...1.3.6)

* :arrow_up: Bump fiona from 1.8.21 to 1.9.1

Bumps [fiona](https://github.com/Toblerity/Fiona) from 1.8.21 to 1.9.1.
- [Release notes](https://github.com/Toblerity/Fiona/releases)
- [Changelog](https://github.com/Toblerity/Fiona/blob/master/CHANGES.txt)
- [Commits](https://github.com/Toblerity/Fiona/compare/1.8.21...1.9.1)

* :arrow_up: Bump pyogrio from 0.4.0 to 0.5.1

Bumps [pyogrio](https://github.com/geopandas/pyogrio) from 0.4.0 to 0.5.1.
- [Release notes](https://github.com/geopandas/pyogrio/releases)
- [Changelog](https://github.com/geopandas/pyogrio/blob/v0.4.0/CHANGES.md)
- [Commits](https://github.com/geopandas/pyogrio/compare/v0.4.0...v0.5.1)

* :arrow_up: Bump toolz from 0.11.2 to 0.12.0

Bumps [toolz](https://github.com/pytoolz/toolz) from 0.11.2 to 0.12.0.
- [Release notes](https://github.com/pytoolz/toolz/releases)
- [Changelog](https://github.com/pytoolz/toolz/blob/master/release-notes)
- [Commits](https://github.com/pytoolz/toolz/compare/0.11.2...0.12.0)

Fixes `AttributeError: 'TlzSpec' object has no attribute '_uninitialized_submodules'`, xref https://github.com/pytoolz/toolz/pull/533

* :arrow_up: Bump shapely from 1.8.2 to 2.0.1

Bumps [shapely](https://github.com/shapely/shapely) from 1.8.2 to 2.0.1.
- [Release notes](https://github.com/shapely/shapely/releases)
- [Changelog](https://github.com/shapely/shapely/blob/2.0.1/CHANGES.txt)
- [Commits](https://github.com/shapely/shapely/compare/1.8.2...2.0.1)

* :construction_worker: NEP29: Run Continuous Integration on Python 3.11

Bumps [python](https://github.com/python/cpython) from 3.10.10 to 3.11.2.
  - [Release notes](https://github.com/python/cpython/releases/tag/v3.11.2)
  - [Changelog](https://docs.python.org/3/whatsnew/3.11.html)
  - [Commits](https://github.com/python/cpython/compare/v3.10.10...v3.11.2)

* :triangular_flag_on_post: Skip Ubuntu Python 3.11 CI tests for draft PRs

Conserve GitHub Actions Continuous Integration resources when a Pull Request is in draft mode.