:pushpin: Temporarily pin torchdata to 0.4.1 on readthedocs build
The latest torchdata=0.5.0 version installed via readthedocs has a bug with `torchdata.datapipes.utils.to_graph` raising `AttributeError: 'tuple' object has no attribute 'items'`. This has been fixed in https://github.com/pytorch/data/pull/872, but need to wait for torchdata=0.5.1 or later to be released, so keep using torchdata=0.4.1 for now.