:pushpin: Temporarily pin numpy<1.24 to prevent AttributeError
The latest numpy=1.24 version installed via readthedocs is incompatible with datashader=0.14.4, resulting in an error like `AttributeError: module 'numpy' has no attribute 'warnings'`. This was reported in https://github.com/holoviz/datashader/issues/1209 and fixed in https://github.com/holoviz/datashader/pull/1176, but will need to wait for datashader>=0.14.5 to be released.