:pushpin: Pin minimum xbatcher version to 0.2.0 (#73)
Using xbatcher v0.2.0 which comes with better handling of xarray.DataArray/xarray.Dataset inputs/outputs. Allows removal of a workaround with the xarray.DataArray name not being set (when being force converted to an xarray.Dataset in xbatcher=0.1.0). Lots of simplied code in tutorials too, as xarray.DataArray objects are being returned rather than xarray.Dataset.

* :pushpin: Pin minimum xbatcher version to 0.2.0

Bumps [xbatcher](https://github.com/xarray-contrib/xbatcher) from 0.1.0 to 0.2.0.
- [Release notes](https://github.com/xarray-contrib/xbatcher/releases)
- [Commits](https://github.com/xarray-contrib/xbatcher/compare/0.1.0...v0.2.0)

* :white_check_mark: Fix xbatcher doctest returning DataArray not Dataset

Slicing an `xarray.DataArray` with xbatcher=0.2.0 now returns an `xarray.DataArray` instead of an `xarray.Dataset`!

* :alien: Remove set name workaround when converting DataArray to Dataset

Since `xarray.DataArray` objects are not converted to `xarray.Dataset` objects anymore in xbatcher=0.2.0, the hacky roundtrip workaround added in 147f2704e1896e9fab4065e943500133bf6f2c24 can be removed.

* :art: Remove data_vars.get from collate functions

No need to turn those `xarray.Dataset` objects to `xarray.DataArray` anymore using `.data_vars.get(key="__xarray_dataarray_variable__")`! Simplifies all those custom xarray collate functions and the raster plotting code. Also fixed a typo in vector-segmentation-masks.md.

* :pushpin: Temporarily pin torchdata to 0.4.1 on readthedocs build

The latest torchdata=0.5.0 version installed via readthedocs has a bug with `torchdata.datapipes.utils.to_graph` raising `AttributeError: 'tuple' object has no attribute 'items'`. This has been fixed in https://github.com/pytorch/data/pull/872, but need to wait for torchdata=0.5.1 or later to be released, so keep using torchdata=0.4.1 for now.

* :pencil2: Update documentation to say raster chips are xr.DataArray objs

Convert `xr.Dataset` to `xr.DataArray` in some of the docstrings and type hints of functions in the walkthrough tutorials, since the raster images returned by `xbatcher=0.2.0` are now `xarray.DataArray` objects if `xarray.DataArray` inputs are passed in.